
'use server';
/**
 * @fileOverview An AI flow for generating a detailed tax and performance report.
 *
 * - getTaxReport - A function that handles report generation.
 * - TaxReportInput - The input type for the function.
 * - TaxReportOutput - The return type for the function.
 */

import { z } from '@genkit-ai/core';
import type { WalletData, Transaction, Currency, Holding } from '@/lib/types';
import { eachDayOfInterval, startOfDay, isWithinInterval, format, subDays, addDays, differenceInDays } from 'date-fns';

// The input schema for the tax report flow
const TaxReportInputSchema = z.object({
  walletData: z.string().describe('JSON string of the full WalletData object.'),
  startDate: z.string().describe('Start date for the report in ISO 8601 format.'),
  endDate: z.string().describe('End date for the report in ISO 8601 format.'),
  currency: z.string().describe('The currency for the report (e.g., "USD").'),
});
export type TaxReportInput = z.infer<typeof TaxReportInputSchema>;

// The output schema, which will now be generated by code, not AI.
const TaxReportOutputSchema = z.object({
  summary: z.object({
    startDate: z.string().describe('Start date of the report.'),
    endDate: z.string().describe('End date of the report.'),
    startValue: z.number().describe('Total portfolio value in the specified currency at the start of the period.'),
    endValue: z.number().describe('Total portfolio value in the specified currency at the end of the period.'),
    totalValueChange: z.number().describe('The absolute change in portfolio value.'),
    totalValueChangePercentage: z.number().describe('The percentage change in portfolio value.'),
    costBasis: z.number().describe("The total cost of acquiring the assets held at the end of the period."),
    unrealizedGains: z.number().describe("The potential profit or loss if all assets were sold at the end of the period."),
    inflow: z.number().describe('Total value of assets received during the period.'),
    outflow: z.number().describe('Total value of assets sent during the period.'),
    tradingFees: z.number().describe('Total transaction fees paid for sent transactions during the period.'),
    realizedGains: z.number().describe('The profit or loss locked in from selling or spending assets during the period.'),
  }),
  portfolioHistory: z.array(z.object({
    date: z.string().describe('The date for this data point in ISO 8601 format.'),
    totalValue: z.number().describe('The total portfolio value in the specified currency on this date.'),
    costBasis: z.number().describe('The cost basis on this date.'),
  })).describe('An array of historical data points for the portfolio chart.'),
  holdings: z.array(z.object({
    address: z.string().describe('The Bitcoin address holding the balance.'),
    balance: z.number().describe('The quantity of the asset held in this address.'),
    cost: z.number().describe('The total cost basis for the assets in this address.'),
    marketValue: z.number().describe('The current market value of the assets in this address.'),
    roi: z.number().describe('The return on investment percentage for the assets in this address.'),
    potentialGain: z.number().describe('The potential gain or loss on this holding.'),
  })).describe('A list of addresses and their holdings at the end of the period.'),
});

export type TaxReportOutput = z.infer<typeof TaxReportOutputSchema>;

async function getDailyPrices(startDate: Date, endDate: Date, currency: Currency): Promise<Record<string, number>> {
    const prices: Record<string, number> = {};
    
    // Ensure consistent date handling - use startOfDay for all date comparisons
    const today = startOfDay(new Date());
    // Use 364 days instead of 365 to account for inclusive date counting in CoinGecko API
    const maxAllowedStartDate = subDays(today, 364);
    
    // Check if the requested range exceeds CoinGecko's 364-day limit
    if (startDate < maxAllowedStartDate) {
        const requestedDays = differenceInDays(endDate, startDate);
        const availableDays = differenceInDays(endDate, maxAllowedStartDate);
        
        if (requestedDays > 364) {
            console.warn(`CoinGecko API: Requested ${requestedDays} days of data, but only ${availableDays} days are available due to 364-day limit.`);
            console.warn(`Data will be provided from ${format(maxAllowedStartDate, 'yyyy-MM-dd')} to ${format(endDate, 'yyyy-MM-dd')}`);
        }
        
        // If both dates are older than 364 days, throw an error
        if (endDate < maxAllowedStartDate) {
            throw new Error(`CoinGecko API: Both start date (${format(startDate, 'yyyy-MM-dd')}) and end date (${format(endDate, 'yyyy-MM-dd')}) are older than 364 days. Historical data is not available for this range.`);
        }
    }
    
    // Strictly enforce the 364-day limit - never request data older than this
    const finalStartDate = startDate < maxAllowedStartDate ? maxAllowedStartDate : startDate;
    
    console.log(`CoinGecko API: Requesting data from ${format(finalStartDate, 'yyyy-MM-dd')} to ${format(endDate, 'yyyy-MM-dd')}`);
    
    let currentStartDate = finalStartDate;

    try {
        while (currentStartDate <= endDate) {
            
            let currentEndDate = addDays(currentStartDate, 90);
            if (currentEndDate > endDate) {
                currentEndDate = endDate;
            }

            const fromTimestamp = Math.floor(currentStartDate.getTime() / 1000);
            // Add a small buffer to the end timestamp to ensure it's always greater, preventing API errors for single-day ranges.
            const toTimestamp = Math.floor(currentEndDate.getTime() / 1000) + 3600;

            const url = `https://api.coingecko.com/api/v3/coins/bitcoin/market_chart/range?vs_currency=${currency.toLowerCase()}&from=${fromTimestamp}&to=${toTimestamp}`;
            const headers: HeadersInit = { 'Accept': 'application/json' };
            const apiKey = process.env.COINGECKO_API_KEY;
            if (apiKey) {
                headers['x-cg-demo-api-key'] = apiKey;
            } else {
                console.warn("The CoinGecko API key is missing. Public API may have rate limits.");
            }

            const response = await fetch(url, { headers, next: { revalidate: 3600 } });
            if (!response.ok) {
                const errorBody = await response.text();
                console.error(`CoinGecko request for chunk ${format(currentStartDate, 'yyyy-MM-dd')} failed with status ${response.status}:`, errorBody);
                throw new Error(`Failed to fetch historical prices from CoinGecko. Status: ${response.status}`);
            }

            const data = await response.json();

            for (const [timestamp, price] of data.prices) {
                const dateKey = format(startOfDay(new Date(timestamp)), 'yyyy-MM-dd');
                prices[dateKey] = price;
            }
            currentStartDate = addDays(currentEndDate, 1);
        }
        return prices;
    } catch (error) {
        console.error("Error in getDailyPrices:", error);
        throw new Error("Failed to fetch historical prices from CoinGecko. The request was invalid (status: unknown). This may be due to an issue with the date range or currency.");
    }
}


/**
 * Generates a financial report by performing calculations directly on the wallet data.
 * This function no longer relies on an AI model for calculations to ensure accuracy and consistency.
 */
export async function getTaxReport(input: TaxReportInput): Promise<TaxReportOutput> {
    try {
        const { walletData: walletDataString, startDate: startDateString, endDate: endDateString, currency: currencyUpper } = input;
        const currency = currencyUpper as Currency;
        const walletData: WalletData = JSON.parse(walletDataString);
        const startDate = startOfDay(new Date(startDateString));
        const endDate = startOfDay(new Date(endDateString));
        
        // Sort all transactions from oldest to newest for chronological processing
        const allTransactions = [...walletData.transactions].sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
        
        // Fetch daily prices for the entire range
        const dailyPrices = await getDailyPrices(startDate, endDate, currency);
        const latestPrice = walletData.btcPrices[currency]?.last || 0;

        // --- Calculation State ---
        let totalCostBasis = 0;
        let totalBtc = 0;
        let realizedGainsDuringPeriod = 0;
        let inflowDuringPeriod = 0;
        let outflowDuringPeriod = 0;
        let tradingFeesDuringPeriod = 0;

        const balanceHistory: Record<string, { btc: number; costBasis: number }> = {};
        
        // --- Process All Transactions Chronologically to build up state ---
        for (const tx of allTransactions) {
            const txDate = startOfDay(new Date(tx.date));
            const dateKey = format(txDate, 'yyyy-MM-dd');
            const historicalPrice = tx.historicalPrice || dailyPrices[dateKey] || latestPrice;
            const txValue = Math.abs(tx.btc) * historicalPrice;

            if (tx.btc > 0) { // Received
                totalCostBasis += txValue;
                totalBtc += tx.btc;
            } else { // Sent
                if (totalBtc > 0) {
                    const avgCostPerBtc = totalCostBasis / totalBtc;
                    const costOfBtcSpent = Math.abs(tx.btc) * avgCostPerBtc;
                    
                    if (isWithinInterval(txDate, { start: startDate, end: endDate })) {
                        realizedGainsDuringPeriod += txValue - costOfBtcSpent;
                    }
                    totalCostBasis -= costOfBtcSpent;
                }
                totalBtc += tx.btc; // btc is negative here
            }
            totalBtc = Math.max(0, totalBtc); // Prevent negative balance
            totalCostBasis = Math.max(0, totalCostBasis); // Prevent negative cost basis

            balanceHistory[dateKey] = { btc: totalBtc, costBasis: totalCostBasis };

            if (isWithinInterval(txDate, { start: startDate, end: endDate })) {
                if (tx.btc > 0) {
                    inflowDuringPeriod += txValue;
                } else {
                    outflowDuringPeriod += txValue;
                    tradingFeesDuringPeriod += (tx.fee / 1e8) * historicalPrice;
                }
            }
        }

        // --- Create a complete daily history for the selected date range ---
        const dateInterval = eachDayOfInterval({ start: startDate, end: endDate });
        let lastKnownBtc = 0;
        let lastKnownCostBasis = 0;

        // Find the initial state just before the start date
        const transactionsBeforeStartDate = allTransactions.filter(tx => new Date(tx.date) < startDate);
        if (transactionsBeforeStartDate.length > 0) {
            let initialBtc = 0;
            let initialCost = 0;
            for(const tx of transactionsBeforeStartDate) {
                const txValue = Math.abs(tx.btc) * (tx.historicalPrice || 0);
                 if (tx.btc > 0) {
                    initialBtc += tx.btc;
                    initialCost += txValue;
                } else {
                    if (initialBtc > 0) {
                        const avgCost = initialCost / initialBtc;
                        initialCost -= Math.abs(tx.btc) * avgCost;
                    }
                    initialBtc += tx.btc;
                }
            }
            lastKnownBtc = Math.max(0, initialBtc);
            lastKnownCostBasis = Math.max(0, initialCost);
        }

        const portfolioHistory = dateInterval.map(day => {
            const dateKey = format(day, 'yyyy-MM-dd');
            if (balanceHistory[dateKey]) {
                lastKnownBtc = balanceHistory[dateKey].btc;
                lastKnownCostBasis = balanceHistory[dateKey].costBasis;
            }
            const price = dailyPrices[dateKey] || (isWithinInterval(day, {start: subDays(new Date(), 1), end: new Date()}) ? latestPrice : 0);
            return {
                date: day.toISOString(),
                totalValue: lastKnownBtc * price,
                costBasis: lastKnownCostBasis,
            };
        });
        
        // --- Calculate final summary stats ---
        const startValue = portfolioHistory.length > 0 ? portfolioHistory[0].totalValue : 0;
        const endValue = totalBtc * latestPrice;
        const unrealizedGains = endValue - totalCostBasis;
        const totalValueChange = endValue - startValue;
        const totalValueChangePercentage = startValue > 0 ? (totalValueChange / startValue) * 100 : 0;
        
        // --- Calculate final holdings by address ---
        const addressBalances: { [address: string]: { balance: number } } = {};

        // Start with known address balances (in sats) to ensure holdings are populated
        for (const addressInfo of walletData.addresses) {
            const btcBalance = addressInfo.balance / 1e8;
            if (btcBalance > 0) {
                addressBalances[addressInfo.address] = { balance: btcBalance };
            }
        }

        // Enrich with UTXO data (also in sats) to capture spendable outputs
        for (const utxo of walletData.utxos) {
            if (!addressBalances[utxo.address]) {
                addressBalances[utxo.address] = { balance: 0 };
            }
            const btcValue = utxo.value / 1e8;
            addressBalances[utxo.address].balance += btcValue;
        }

        // Fallback: if no per-address data is available but the wallet has a balance, use an aggregate entry
        if (Object.keys(addressBalances).length === 0 && totalBtc > 0) {
            addressBalances['Aggregated Wallet'] = { balance: totalBtc };
        }

        const holdings: Holding[] = Object.entries(addressBalances).map(([address, data]) => {
            const cost = totalBtc > 0 ? data.balance * (totalCostBasis / totalBtc) : 0;
            const marketValue = data.balance * latestPrice;
            const potentialGain = marketValue - cost;
            const roi = cost > 0 ? (potentialGain / cost) * 100 : 0;
            return {
                address,
                balance: data.balance,
                cost,
                marketValue,
                roi,
                potentialGain,
            };
        });

        const report: TaxReportOutput = {
            summary: {
                startDate: startDate.toISOString(),
                endDate: endDate.toISOString(),
                startValue,
                endValue,
                totalValueChange,
                totalValueChangePercentage,
                costBasis: totalCostBasis,
                unrealizedGains,
                inflow: inflowDuringPeriod,
                outflow: outflowDuringPeriod,
                tradingFees: tradingFeesDuringPeriod,
                realizedGains: realizedGainsDuringPeriod,
            },
            portfolioHistory,
            holdings,
        };

        return report;
        
    } catch (e: any) {
        console.error("Critical error in getTaxReport:", e);
        throw new Error(e.message || "An unexpected error occurred while generating the report.");
    }
}
